set(MCU_FAMILY tiny)
set(MCU_TYPE   2313)

set(CMAKE_SYSTEM_NAME Generic)

set(CMAKE_C_COMPILER avr-gcc)
set(CMAKE_CXX_COMPILER avr-g++)

set(CMAKE_C_FLAGS -mmcu=at${MCU_FAMILY}${MCU_TYPE})
set(CMAKE_CXX_FLAGS -mmcu=at${MCU_FAMILY}${MCU_TYPE})

string(TOUPPER ${MCU_TYPE} MCU_TYPE)
add_definitions( -D__AVR_AT${MCU_FAMILY}${MCU_TYPE}__ )

set(CMAKE_FIND_ROOT_PATH /usr/avr-gcc)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
